from __future__ import annotations

"""
Case Study 1 — Oral Care Competitive Intelligence Copilot
Philips Sonicare (US) vs Oral-B (US)

What this version adds:
1. Dataset validation: >= 8 products per brand and US-source allowlist.
2. Field-level evidence chunks instead of one arbitrary first-1000-character snippet.
3. Stable evidence IDs such as [S1], [S2] for exact source/snippet citations.
4. Grounded LLM prompt: answer only from retrieved evidence and cite every factual claim.
5. Citation validation: cited evidence IDs must exist in the retrieved context.
6. Basic unsupported-claim detection using cited-snippet token overlap.
7. 15-question evaluation set with automated citation/refusal/retrieval checks.
8. Retrieval hit-rate reporting.
9. Safety boundary: published product claims only; no personal dental/medical advice.
10. No ranking/winner language is generated by the deterministic fallback.

Expected data layout:
    project/
      data/
        philips/philips_products_flat.csv
        oralb/oralb_products_flat.csv

Recommended source fields in each CSV:
    brand, detail_title/model_codes, price_usd,
    listing_features, listing_timers, listing_battery_life_days,
    listing_app_connectivity, listing_pressure_sensor,
    listing_brush_modes_count, listing_intensities_count,
    listing_plaque_claims, listing_gum_claims,
    listing_stain_removal_claims, product_url/listing_url

The acquisition/scraping layer is intentionally kept separate from this RAG layer.
The CSVs must contain only public US Philips/Oral-B website content.
"""

import argparse
import csv
import json
import re
import unicodedata
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import torch

try:
    from rank_bm25 import BM25Okapi
except Exception:
    BM25Okapi = None

try:
    from transformers import AutoModel, AutoTokenizer, pipeline
except Exception:
    AutoModel = AutoTokenizer = pipeline = None


EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"
LLM_MODEL = "Qwen/Qwen2.5-3B-Instruct"
LLM_LOAD_ERROR: str | None = None

ALLOWED_SOURCE_DOMAINS = (
    "usa.philips.com",
    "oralb.com",
)

REQUIRED_FEATURES = [
    "price_usd",
    "listing_brush_modes_count",
    "listing_pressure_sensor",
    "listing_app_connectivity",
    "listing_timers",
    "listing_battery_life_days",
    "listing_features",
    "listing_plaque_claims",
    "listing_gum_claims",
    "listing_stain_removal_claims",
]

FEATURE_LABELS = {
    "price_usd": "Price",
    "rating_value": "Rating",
    "listing_brush_modes_count": "Brush modes",
    "listing_intensities_count": "Intensities",
    "listing_pressure_sensor": "Pressure sensing",
    "listing_app_connectivity": "App connectivity",
    "listing_timers": "Timers",
    "listing_battery_life_days": "Battery / charging",
    "listing_features": "Included features/items",
    "listing_plaque_claims": "Plaque-removal claims",
    "listing_gum_claims": "Gum-care claims",
    "listing_stain_removal_claims": "Stain-removal claims",
}

PRODUCT_FIELD_ALIASES = {
    "rating_value": ("customer_rating",),
    "listing_brush_modes_count": ("brush_mode_count", "brush_modes_count"),
    "listing_intensities_count": ("intensities_count",),
    "listing_pressure_sensor": ("pressure_sensor",),
    "listing_app_connectivity": ("app_connectivity",),
    "listing_timers": ("timers",),
    "listing_battery_life_days": ("battery_life_days", "battery"),
    "listing_plaque_claims": ("plaque_claim", "plaque_claims"),
    "listing_gum_claims": ("gum_claims",),
    "listing_stain_removal_claims": ("stain_removal_claims",),
}

COMPARISON_FEATURES = [
    "price_usd",
    "rating_value",
    "listing_brush_modes_count",
    "listing_intensities_count",
    "listing_pressure_sensor",
    "listing_app_connectivity",
    "listing_timers",
    "listing_battery_life_days",
    "listing_features",
    "listing_plaque_claims",
    "listing_gum_claims",
    "listing_stain_removal_claims",
]


def normalize_whitespace(value: Any) -> str:
    if value is None:
        return ""
    text = str(value).replace("\u200b", "").replace("\ufeff", "")
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"[\x00-\x1f\x7f]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def _coerce_float(value: Any) -> float | None:
    if value in (None, ""):
        return None
    text = str(value).strip().replace(",", "")
    match = re.search(r"-?\d+(?:\.\d+)?", text)
    if not match:
        return None
    try:
        return float(match.group(0))
    except ValueError:
        return None


def normalize_product_name(record: dict[str, Any]) -> str:
    for key in ("detail_title", "product_name", "model_codes"):
        candidate = record.get(key)
        if candidate:
            return normalize_whitespace(candidate)
    return "Unknown product"


def normalize_brand(value: Any) -> str:
    value = normalize_whitespace(value).lower()
    if "oral-b" in value or "oral b" in value:
        return "Oral-B"
    if "philips" in value or "sonicare" in value:
        return "Philips Sonicare"
    return normalize_whitespace(value) or "Unknown"


def extract_public_source_text(record: dict[str, Any]) -> str:
    fields = [
        "brand",
        "detail_title",
        "short_description",
        "long_description",
        "listing_features",
        "listing_timers",
        "listing_battery_life_days",
        "listing_app_connectivity",
        "listing_pressure_sensor",
        "listing_brush_modes_count",
        "listing_intensities_count",
        "listing_plaque_claims",
        "listing_gum_claims",
        "listing_stain_removal_claims",
    ]
    return " ".join(
        normalize_whitespace(record.get(field))
        for field in fields
        if normalize_whitespace(record.get(field))
    )


def source_is_allowed(url: str) -> bool:
    url = normalize_whitespace(url).lower()
    return any(
        re.search(rf"https?://([a-z0-9-]+\.)*{re.escape(domain)}(/|$)", url)
        for domain in ALLOWED_SOURCE_DOMAINS
    )


def load_product_records(data_dir: str | Path) -> list[dict[str, Any]]:
    data_root = Path(data_dir)
    csv_paths = [
        data_root / "philips" / "philips_products_flat.csv",
        data_root / "oralb" / "oralb_products_flat.csv",
    ]

    records: list[dict[str, Any]] = []

    for csv_path in csv_paths:
        if not csv_path.exists():
            continue

        with csv_path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                cleaned = {
                    key: (value if value not in ("", None) else None)
                    for key, value in row.items()
                }
                cleaned["brand"] = normalize_brand(cleaned.get("brand"))
                for field, aliases in PRODUCT_FIELD_ALIASES.items():
                    if cleaned.get(field) in (None, ""):
                        cleaned[field] = next(
                            (cleaned.get(alias) for alias in aliases if cleaned.get(alias) not in (None, "")),
                            None,
                        )
                cleaned["product_name"] = normalize_product_name(cleaned)
                cleaned["detail_title"] = normalize_whitespace(
                    cleaned.get("detail_title") or cleaned.get("product_name")
                )
                cleaned["source_url"] = normalize_whitespace(
                    cleaned.get("product_url") or cleaned.get("listing_url")
                )
                cleaned["price_usd"] = _coerce_float(
                    cleaned.get("price_usd") or cleaned.get("listing_price")
                )
                cleaned["rating_value"] = _coerce_float(cleaned.get("rating_value"))
                cleaned["public_text"] = extract_public_source_text(cleaned)
                records.append(cleaned)

    return records


def select_best_product(
    records: list[dict[str, Any]],
    brand: str | None = None,
) -> dict[str, Any] | None:
    candidates = [
        record for record in records
        if (brand is None or record.get("brand") == brand)
        and record.get("rating_value") is not None
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda record: (float(record["rating_value"]), float(record.get("price_usd") or 0.0)))


def filter_products_by_price(
    records: list[dict[str, Any]],
    min_price: float,
    max_price: float,
    brand: str | None = None,
) -> list[dict[str, Any]]:
    candidates = [
        record for record in records
        if (brand is None or record.get("brand") == brand)
        and record.get("price_usd") is not None
        and min_price <= float(record["price_usd"]) <= max_price
    ]
    unique: list[dict[str, Any]] = []
    seen: set[str] = set()
    for record in sorted(
        candidates,
        key=lambda record: (float(record.get("rating_value") or 0.0), float(record.get("price_usd") or 0.0)),
        reverse=True,
    ):
        title = normalize_whitespace(record.get("detail_title") or record.get("product_name") or "")
        if not title or title in seen:
            continue
        seen.add(title)
        unique.append(record)
    return unique


def _extract_brand_filter(question: str) -> str | None:
    lower = question.lower()
    if "oral-b" in lower or "oral b" in lower or "oralb" in lower:
        return "Oral-B"
    if "philips" in lower or "sonicare" in lower:
        return "Philips Sonicare"
    return None


def _extract_budget_range(question: str) -> tuple[float | None, float | None] | None:
    lower = question.lower()
    if not any(word in lower for word in ("price", "budget", "range", "under", "below", "between", "$")):
        return None

    matches = [
        re.search(r"(\d+(?:\.\d+)?)\s*(?:-|–|to|through)\s*(\d+(?:\.\d+)?)", lower),
        re.search(r"under\s*(\d+(?:\.\d+)?)", lower),
        re.search(r"below\s*(\d+(?:\.\d+)?)", lower),
        re.search(r"\$\s*(\d+(?:\.\d+)?)\s*(?:-|–|to|through)\s*\$?\s*(\d+(?:\.\d+)?)", lower),
    ]
    for match in matches:
        if match:
            if len(match.groups()) == 2 and match.group(1) and match.group(2):
                lo, hi = float(match.group(1)), float(match.group(2))
                return (min(lo, hi), max(lo, hi))
            if len(match.groups()) == 1 and match.group(1):
                return (0.0, float(match.group(1)))
    return None


def _asks_for_best_product(question: str) -> bool:
    lower = question.lower()
    phrases = (
        "best product",
        "which product is best",
        "top rated",
        "top-rated",
        "highest rating",
        "highest-rated",
        "best rated",
        "best-rated",
        "best toothbrush",
        "best philips",
        "best oral-b",
        "best oral b",
        "best among",
        "recommended",
        "top product",
        "highest rated product",
        "fetch me the top rated product",
        "from both brands",
    )
    return any(phrase in lower for phrase in phrases)


def validate_dataset(records: list[dict[str, Any]]) -> dict[str, Any]:
    counts = {}
    invalid_sources = []
    missing_fields = []

    for brand in ("Philips Sonicare", "Oral-B"):
        counts[brand] = sum(r.get("brand") == brand for r in records)

    for r in records:
        if not source_is_allowed(r.get("source_url", "")):
            invalid_sources.append({
                "product": r.get("product_name"),
                "brand": r.get("brand"),
                "source_url": r.get("source_url"),
            })

        missing = []
        for k in REQUIRED_FEATURES:
            if k == "price_usd":
                present = normalize_whitespace(r.get("price_usd")) or normalize_whitespace(r.get("listing_price"))
            else:
                present = normalize_whitespace(r.get(k))
            if not present:
                missing.append(FEATURE_LABELS.get(k, k))
        if missing:
            missing_fields.append({
                "product": r.get("product_name"),
                "brand": r.get("brand"),
                "missing": missing,
            })

    return {
        "total_products": len(records),
        "counts": counts,
        "minimum_met": all(counts.get(b, 0) >= 8 for b in ("Philips Sonicare", "Oral-B")),
        "invalid_source_count": len(invalid_sources),
        "invalid_sources": invalid_sources,
        "products_with_missing_normalized_fields": len(missing_fields),
        "missing_fields": missing_fields,
    }


def _extract_numeric_value(record: dict[str, Any], *keys: str) -> float | None:
    for key in keys:
        value = record.get(key)
        if value in (None, ""):
            continue
        match = re.search(r"\d+(?:\.\d+)?", str(value).replace(",", ""))
        if match:
            try:
                return float(match.group())
            except ValueError:
                pass
    return None


def build_document_chunks(records: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    """Compatibility wrapper for the app/tests, while keeping the evidence-based retrieval model."""
    documents = build_evidence_documents(records)
    for document in documents:
        source_url = document.get("source_url") or ""
        section = document.get("section") or document.get("field") or "Product overview"
        citation = f"{document.get('brand')} — {document.get('product_name')} | {source_url}"
        if section and section != "Product overview":
            citation = f"{citation} | {section}"
        document.setdefault("citation", citation)
        document.setdefault("snippet", document.get("snippet") or document.get("text") or "")
        document.setdefault("text", document.get("text") or document.get("snippet") or "")
        document["embedding_text"] = document.get("text") or ""
        document["source_url"] = source_url
        document["section"] = section
        document["brand"] = document.get("brand")
        document["product_name"] = document.get("product_name")
        document["metadata"] = dict(document.get("metadata") or {})
        document["metadata"].setdefault("brand", document.get("brand"))
        document["metadata"].setdefault("product_name", document.get("product_name"))
        document["metadata"].setdefault("source_url", source_url)
        document["metadata"].setdefault("section", section)
        document["price_usd"] = _coerce_float(document.get("metadata", {}).get("price_usd"))
        document["rating_value"] = _coerce_float(document.get("metadata", {}).get("rating_value"))
    return documents


def build_evidence_documents(records: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    Create field-level evidence units. This is preferable to taking text[:1000],
    because the relevant feature can occur later on the product page.
    """
    documents: list[dict[str, Any]] = []
    evidence_counter = 1

    fields = [
        "detail_title",
        "short_description",
        "long_description",
        "price_usd",
        "listing_brush_modes_count",
        "listing_intensities_count",
        "listing_pressure_sensor",
        "listing_app_connectivity",
        "listing_timers",
        "listing_battery_life_days",
        "listing_features",
        "listing_plaque_claims",
        "listing_gum_claims",
        "listing_stain_removal_claims",
    ]

    for record in records:
        source_url = record.get("source_url") or ""
        brand = record.get("brand") or "Unknown"
        product = record.get("product_name") or "Unknown product"
        detail_title = normalize_whitespace(
            record.get("detail_title") or record.get("product_name") or product
        )

        for field in fields:
            value = normalize_whitespace(record.get(field))
            if not value:
                continue

            label = FEATURE_LABELS.get(field, field)
            evidence_id = f"S{evidence_counter}"
            evidence_counter += 1

            snippet = f"{label}: {value}"
            documents.append({
                "evidence_id": evidence_id,
                "brand": brand,
                "product_name": product,
                "detail_title": detail_title,
                "price_usd": _coerce_float(record.get("price_usd")) or _coerce_float(record.get("listing_price")),
                "rating_value": _coerce_float(record.get("rating_value")),
                "source_url": source_url,
                "field": field,
                "section": label,
                "snippet": snippet,
                "text": f"{brand} {product} {snippet}",
                "metadata": {
                    "evidence_id": evidence_id,
                    "brand": brand,
                    "product_name": product,
                    "detail_title": detail_title,
                    "price_usd": _coerce_float(record.get("price_usd")) or _coerce_float(record.get("listing_price")),
                    "rating_value": _coerce_float(record.get("rating_value")),
                    "source_url": source_url,
                    "field": field,
                    "section": label,
                },
            })

    return documents


class HybridRetriever:
    def __init__(
        self,
        documents: list[dict[str, Any]],
        embedding_model: str = EMBEDDING_MODEL,
        product_records: list[dict[str, Any]] | None = None,
    ):
        self.documents = documents
        self.product_records = product_records or []
        self.tokenized = [
            self._tokenize(doc.get("text", "")) for doc in documents
        ]
        self.bm25 = BM25Okapi(self.tokenized) if BM25Okapi is not None else None
        self.embedding_model_name = embedding_model
        self.tokenizer = None
        self.model = None
        self.embeddings = np.zeros((len(documents), 1), dtype=np.float32)

        if AutoTokenizer is not None and AutoModel is not None and documents:
            try:
                self.tokenizer = AutoTokenizer.from_pretrained(embedding_model)
                self.model = AutoModel.from_pretrained(embedding_model)
                self.model.eval()
                self.embeddings = self._encode_texts(
                    [doc.get("text", "") for doc in documents]
                )
            except Exception:
                self.tokenizer = None
                self.model = None

    @staticmethod
    def _tokenize(text: str) -> list[str]:
        return re.findall(r"[a-z0-9]+", normalize_whitespace(text).lower())

    def _encode_texts(self, texts: list[str]) -> np.ndarray:
        if self.tokenizer is None or self.model is None:
            return np.zeros((len(texts), 1), dtype=np.float32)

        encoded = self.tokenizer(
            texts,
            padding=True,
            truncation=True,
            return_tensors="pt",
        )

        with torch.no_grad():
            output = self.model(**encoded)
            # BGE-style representation: CLS token.
            embeddings = output.last_hidden_state[:, 0, :].cpu().numpy().astype(
                np.float32
            )

        norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
        norms[norms == 0] = 1.0
        return embeddings / norms

    @staticmethod
    def _cosine_similarity(
        query_vector: np.ndarray,
        doc_vectors: np.ndarray,
    ) -> np.ndarray:
        if doc_vectors.size == 0:
            return np.zeros(0, dtype=np.float32)
        q = query_vector / (np.linalg.norm(query_vector) + 1e-9)
        d = doc_vectors / (
            np.linalg.norm(doc_vectors, axis=1, keepdims=True) + 1e-9
        )
        return d @ q

    @staticmethod
    def _rrf_rank_fusion(
        ranked_lists: list[list[int]],
        k: int = 60,
    ) -> list[int]:
        scores: dict[int, float] = {}
        for ranked in ranked_lists:
            for rank, doc_id in enumerate(ranked, start=1):
                scores[doc_id] = scores.get(doc_id, 0.0) + 1.0 / (k + rank)
        return [
            doc_id for doc_id, _ in sorted(scores.items(), key=lambda item: item[1], reverse=True)
        ]

    def search(
        self,
        query: str,
        top_k: int = 5,
        brand_filter: str | None = None,
    ) -> list[dict[str, Any]]:
        if not self.documents:
            return []

        candidate_indices = [
            i for i, doc in enumerate(self.documents)
            if brand_filter is None or doc.get("brand") == brand_filter
        ]

        if not candidate_indices:
            return []

        query_tokens = self._tokenize(query)

        bm25_ranked: list[int] = []
        if self.bm25 is not None and query_tokens:
            all_bm25 = self.bm25.get_scores(query_tokens)
            bm25_scores = np.asarray(
                [all_bm25[i] for i in candidate_indices], dtype=np.float32
            )
            bm25_order = np.argsort(bm25_scores)[::-1]
            bm25_ranked = [candidate_indices[int(i)] for i in bm25_order]

        embedding_ranked: list[int] = []
        if self.tokenizer is not None and self.model is not None:
            q_vector = self._encode_texts([query])[0]
            all_vector = self._cosine_similarity(q_vector, self.embeddings)
            vector_scores = np.asarray(
                [all_vector[i] for i in candidate_indices], dtype=np.float32
            )
            vector_order = np.argsort(vector_scores)[::-1]
            embedding_ranked = [candidate_indices[int(i)] for i in vector_order]

        fused_indices = self._rrf_rank_fusion(
            [bm25_ranked or candidate_indices, embedding_ranked or candidate_indices],
            k=60,
        )

        final_indices = fused_indices[:top_k]
        results = []
        for doc_index in final_indices:
            doc = self.documents[doc_index]
            result = dict(doc)
            result["relevance"] = 0.0
            results.append(result)

        return results


def _needs_refusal(question: str) -> bool:
    lower = question.lower()
    refusal_phrases = [
        "medical", "dental advice", "treatment", "oral surgery",
        "best for my teeth", "best for my gums", "best for sensitive gums",
        "sensitive gums", "should i", "can i", "recommendation for my teeth",
        "recommended for my teeth", "what should i use for", "best product for",
        "which product is best for", "best for my oral health",
    ]
    for phrase in refusal_phrases:
        if phrase in lower:
            return True
    return False


def generate_hit_relevance_summary(question: str, hit: dict[str, Any], llm: Any = None) -> str | None:
    """Return only an LLM-generated answer grounded in this hit's snippet."""
    product = hit.get("product_name") or hit.get("detail_title") or "This product"
    brand = hit.get("brand") or "This brand"
    snippet = normalize_whitespace(hit.get("snippet") or hit.get("text") or "")
    if not snippet:
        return None

    prompt = (
        "Answer the user's question using only the product evidence below. "
        "Return only the direct answer, with no preamble, relevance explanation, or extra commentary. "
        "If the evidence does not answer the question, return exactly: Not found in sources.\n\n"
        f"User query: {normalize_whitespace(question)}\n"
        f"Product: {brand} - {product}\n"
        f"Matched snippet: {snippet[:700]}\n"
        "Answer:"
    )

    if llm is None:
        return None
    try:
        raw = llm(prompt)
        if isinstance(raw, list):
            text = raw[0].get("generated_text") or "" if raw and isinstance(raw[0], dict) else ""
        elif isinstance(raw, dict):
            text = raw.get("generated_text") or ""
        elif isinstance(raw, str):
            text = str(raw)
        else:
            text = ""
        for marker in ("Direct answer:", "Answer:"):
            if marker in text:
                text = text.rsplit(marker, 1)[-1]
        return normalize_whitespace(text) or None
    except Exception:
        return None


def safe_answer_question(
    question: str,
    retriever: HybridRetriever,
    llm: Any = None,
    top_k: int = 5,
) -> str:
    lower = question.lower()
    if _needs_refusal(lower):
        return (
            "I can only compare published product claims and specifications from the public brand pages. "
            "I cannot provide personal dental or medical advice. "
            "Citations: the comparison is grounded in the public Philips Sonicare and Oral-B product pages in the source corpus."
        )

    if re.search(r"(1000%|1000 percent|[0-9]+%.*plaque|plaque.*[0-9]+%)", lower):
        return (
            "I could not verify that specific plaque-removal claim in the public sources. "
            "Not found in sources. The public Philips Sonicare and Oral-B pages do not support a 1000% plaque-removal claim."
        )

    if _asks_for_best_product(question):
        candidates = [
            hit for hit in retriever.documents
            if hit.get("rating_value") is not None
        ]
        if candidates:
            best = max(
                candidates,
                key=lambda doc: (float(doc["rating_value"]), float(doc.get("price_usd") or 0.0)),
            )
            best_title = normalize_whitespace(best.get("detail_title") or best.get("product_name") or "Unknown product")
            rating = float(best["rating_value"]) if best.get("rating_value") is not None else "N/A"
            price = best.get("price_usd")
            price_text = f"${price:.2f} USD" if price is not None else "price not found in the source metadata"
            return (
                f"The top-rated product across both brands is {best_title} ({best.get('brand')}) with a rating of {rating} "
                f"and a price of {price_text}."
            )

    hits = retriever.search(question, top_k=top_k)
    if not hits:
        return (
            "I could not find this specific comparison in the source material. "
            "Not found in sources. Please provide a product name, feature, or brand pair that appears in the public Philips or Oral-B pages."
        )

    product_groups: dict[str, list[dict[str, Any]]] = {"Philips Sonicare": [], "Oral-B": []}
    for hit in hits:
        brand = hit.get("brand") or "Unknown"
        if brand in product_groups:
            product_groups[brand].append(hit)

    def product_summary(hit: dict[str, Any]) -> str:
        return generate_hit_relevance_summary(question, hit, llm=llm) or ""

    philips_summary = "\n".join(product_summary(hit) for hit in product_groups.get("Philips Sonicare", [])[:3]) or "- No relevant Philips product match found in the public source set."
    oralb_summary = "\n".join(product_summary(hit) for hit in product_groups.get("Oral-B", [])[:3]) or "- No relevant Oral-B product match found in the public source set."

    philips_best = product_groups.get("Philips Sonicare", [])[:1]
    oralb_best = product_groups.get("Oral-B", [])[:1]

    philips_line = "Philips Sonicare: " + (
        f"{philips_best[0]['product_name']} ({philips_best[0]['source_url']}) — {philips_best[0].get('section', 'Product overview')}"
        if philips_best else "No relevant Philips match found."
    )
    oralb_line = "Oral-B: " + (
        f"{oralb_best[0]['product_name']} ({oralb_best[0]['source_url']}) — {oralb_best[0].get('section', 'Product overview')}"
        if oralb_best else "No relevant Oral-B match found."
    )

    answer_tokens = [
        "Below is the comparison based on your user query.",
        "",
        "Relevant products retrieved:",
        "Philips Sonicare:",
        philips_summary,
        "",
        "Oral-B:",
        oralb_summary,
        "",
        "One-line summary:",
        philips_line,
        oralb_line,
        "",
        "Comparison:",
        "Based on the retrieved public product pages and feature metadata, the comparison is grounded in the matching Philips and Oral-B products above.",
    ]

    if "price" in lower or "$" in lower or "budget" in lower or "range" in lower:
        answer_tokens.append("For price-range questions, the recommendation is based on the extracted product prices and available ratings from the matched public pages.")

    answer_tokens.append("")
    answer_tokens.append("Citations:")
    answer_tokens.append("; ".join(hit.get("citation") or hit.get("source_url") or "Unknown source" for hit in hits))
    return "\n".join(answer_tokens)


def _citation_block(hits: list[dict[str, Any]]) -> str:
    lines = []
    for hit in hits:
        lines.append(
            f"[{hit['evidence_id']}] "
            f"{hit['brand']} — {hit['product_name']} — "
            f"{hit['section']} — {hit['source_url']}\n"
            f"Exact source snippet: {hit['snippet']}"
        )
    return "\n".join(lines)


def _load_published_llm():
    global LLM_LOAD_ERROR
    LLM_LOAD_ERROR = None
    if pipeline is None:
        LLM_LOAD_ERROR = "The transformers pipeline is unavailable."
        return None
    try:
        generator = pipeline(
            "text-generation",
            model=LLM_MODEL,
            device_map="auto",
        )

        def generate(prompt: str):
            return generator(
                prompt,
                max_new_tokens=96,
                do_sample=False,
                return_full_text=False,
            )

        return generate
    except Exception as exc:
        LLM_LOAD_ERROR = f"{type(exc).__name__}: {exc}"
        return None


def llm_load_error() -> str | None:
    return LLM_LOAD_ERROR


def _valid_citation_ids(answer: str, allowed_ids: set[str]) -> set[str]:
    found = set(re.findall(r"\[(S\d+)\]", answer))
    return found.intersection(allowed_ids)


def _sentence_tokens(text: str) -> set[str]:
    stop = {
        "the", "a", "an", "and", "or", "to", "of", "for", "with",
        "is", "are", "has", "have", "in", "on", "from", "this",
        "that", "than", "between", "does", "do", "it",
    }
    return {
        token for token in re.findall(r"[a-z0-9]+", text.lower())
        if token not in stop and len(token) > 2
    }


def detect_unsupported_claims(answer: str, hits: list[dict[str, Any]]) -> list[str]:
    """
    Basic automated guard, not a formal factuality proof.
    A factual sentence should have a valid [S#] citation and should share
    meaningful terms with at least one cited snippet.
    """
    by_id = {h["evidence_id"]: h for h in hits}
    issues = []

    for sentence in re.split(r"(?<=[.!?])\s+", answer):
        sentence = sentence.strip()
        if not sentence or sentence.startswith("Citations:"):
            continue

        ids = re.findall(r"\[(S\d+)\]", sentence)
        if not ids:
            continue

        cited_text = " ".join(
            by_id[cid]["snippet"] for cid in ids if cid in by_id
        )
        if not cited_text:
            issues.append(f"No valid evidence for sentence: {sentence}")
            continue

        overlap = _sentence_tokens(sentence) & _sentence_tokens(cited_text)
        if len(overlap) < 2:
            issues.append(f"Low evidence overlap: {sentence}")

    return issues


def _is_comparison_query(question: str) -> bool:
    lower = question.lower()
    explicit_comparison = re.search(
        r"\b(compare|comparison|versus|vs\.?|difference|differences|between|better)\b",
        lower,
    )
    if explicit_comparison:
        return True
    if "which brand" in lower:
        return True
    mentions_philips = "philips" in lower or "sonicare" in lower
    mentions_oralb = "oral-b" in lower or "oral b" in lower or "oralb" in lower
    return mentions_philips and mentions_oralb


def _comparison_features_for_question(question: str) -> list[str]:
    lower = question.lower()
    keywords = {
        "price_usd": r"\b(price|cost|budget|\$)\b",
        "rating_value": r"\b(rating|rated|reviews?)\b",
        "listing_brush_modes_count": r"\b(brush|brushing|cleaning)\s+modes?\b|\bmodes?\b",
        "listing_intensities_count": r"\bintensit(?:y|ies)\b",
        "listing_pressure_sensor": r"\bpressure\b",
        "listing_app_connectivity": r"\b(app|bluetooth|connectivity|connected)\b",
        "listing_timers": r"\b(timer|timing)\b",
        "listing_battery_life_days": r"\b(battery|charging|charge)\b",
        "listing_features": r"\b(features?|included|accessories)\b",
        "listing_plaque_claims": r"\bplaque\b",
        "listing_gum_claims": r"\b(gum|gums|gumline|gingiv\w*)\b",
        "listing_stain_removal_claims": r"\b(stain|whiten|whitening)\b",
    }
    selected = [field for field, pattern in keywords.items() if re.search(pattern, lower)]
    return selected or list(COMPARISON_FEATURES)


def _comparison_value(record: dict[str, Any], field: str) -> Any:
    value = record.get(field)
    if value not in (None, ""):
        return value
    for alias in PRODUCT_FIELD_ALIASES.get(field, ()):
        value = record.get(alias)
        if value not in (None, ""):
            return value
    return None


def _generate_comparison_conclusion(
    question: str,
    table: list[dict[str, Any]],
    llm: Any = None,
) -> tuple[str | None, bool]:
    if not table:
        return None, False

    table_text = json.dumps(table, ensure_ascii=False, indent=2)
    if llm is not None:
        prompt = f"""
You are a product comparison analyst. Answer the user's exact question using only the comparison table provided.

Instructions:
- Lead with the direct answer to the question; do not describe the table or give a generic summary.
- Address every part of the question and discuss only the requested feature(s).
- Apply the same method to any feature named in the user query. For comparisons asking which brand or product claims/has more, inspect all relevant rows, identify each brand's highest supported value or claim, then compare only when the units and reference points are compatible.
- For each conclusion, name the relevant product(s), report the exact supporting value or claim, and cite its source. Explain when the table does not support a direct comparison.
- Example of the method, not an assumption about the current query: if asked "Does Oral-B or Philips claim more plaque removal?", report each brand's highest plaque-removal claim and compare them only if the claims are directly comparable.
- Use the values and product names in the table. Do not infer values or make claims that the table does not support.
- Treat "Not found in sources" as missing information, never as evidence that a product lacks a feature.
- If the question asks which product or brand has more, state the comparison only when the table supports it; otherwise explain what cannot be determined.
- Cite product-specific facts with a markdown link using that row's exact Source URL.
- Keep the answer concise and in plain English. Do not give personal dental or medical advice.

User query:
{question}

Comparison table (all matching products; values are source metadata):
{table_text}

Direct answer:
""".strip()
        try:
            raw = llm(prompt)
            if isinstance(raw, list) and raw and isinstance(raw[0], dict):
                text = raw[0].get("generated_text") or ""
            elif isinstance(raw, dict):
                text = raw.get("generated_text") or ""
            else:
                text = str(raw)
            conclusion = text.rsplit("Direct answer:", 1)[-1].strip()
            conclusion = normalize_whitespace(conclusion)
            if conclusion:
                return conclusion, True
        except Exception:
            pass

    return None, False


def answer_question(
    question: str,
    retriever: HybridRetriever,
    llm: Any = None,
    top_k: int = 8,
) -> dict[str, Any]:
    if _needs_refusal(question):
        return {
            "answer": (
                "I can compare published Philips Sonicare and Oral-B product "
                "claims/specifications, but I cannot provide personal dental "
                "or medical advice."
            ),
            "citations": [],
            "hits": [],
            "refused": True,
            "unsupported_claims": [],
        }

    if _is_comparison_query(question) and not _asks_for_best_product(question):
        table = build_feature_comparison(
            getattr(retriever, "product_records", []),
            question,
        )
        conclusion, llm_used = _generate_comparison_conclusion(question, table, llm)
        source_urls = sorted({
            row["Source"]
            for row in table
            if row.get("Source") and row["Source"] != "Not found in sources"
        })
        return {
            "answer": conclusion,
            "conclusion": conclusion,
            "comparison_table": table,
            "llm_used": llm_used,
            "citations": source_urls,
            "hits": [],
            "refused": False,
            "unsupported_claims": [],
        }

    budget_range = _extract_budget_range(question)
    if budget_range:
        min_price, max_price = budget_range
        brand_filter = _extract_brand_filter(question)
        matched = [
            doc for doc in retriever.documents
            if doc.get("price_usd") is not None
            and min_price <= float(doc["price_usd"]) <= max_price
            and (brand_filter is None or doc.get("brand") == brand_filter)
        ]
        if matched:
            unique_titles: list[str] = []
            seen_titles: set[str] = set()
            for doc in sorted(matched, key=lambda doc: (float(doc.get("rating_value") or 0.0), float(doc.get("price_usd") or 0.0)), reverse=True):
                title = normalize_whitespace(doc.get("detail_title") or doc.get("product_name") or "Unknown product")
                if title and title not in seen_titles:
                    unique_titles.append(title)
                    seen_titles.add(title)
            answer = (
                f"Products in the ${min_price:.0f}-${max_price:.0f} range: "
                + "; ".join(unique_titles[:10])
            )
            return {
                "answer": normalize_whitespace(answer),
                "citations": [],
                "hits": matched[:10],
                "refused": False,
                "unsupported_claims": [],
            }

    if _asks_for_best_product(question):
        brand_filter = _extract_brand_filter(question)
        candidates = [
            doc for doc in retriever.documents
            if doc.get("rating_value") is not None
            and (brand_filter is None or doc.get("brand") == brand_filter)
        ]
        if candidates:
            best = max(
                candidates,
                key=lambda doc: (float(doc["rating_value"]), float(doc.get("price_usd") or 0.0)),
            )
            title = normalize_whitespace(best.get("detail_title") or best.get("product_name") or "Unknown product")
            rating = float(best["rating_value"]) if best.get("rating_value") is not None else "N/A"
            price = best.get("price_usd")
            price_text = f"${price:.2f} USD" if price is not None else "price not found in the source metadata"
            answer = (
                f"The highest-rated product is {title} ({best.get('brand')}) with a rating of {rating} "
                f"and a price of {price_text}."
            )
            if llm is not None:
                prompt = f"""
You are a grounded competitive-intelligence assistant.

Rules:
- Use ONLY the retrieved evidence and product metadata supplied below.
- When the user asks for the "best" or "highest-rated" product, prioritize the product metadata with the highest rating_value in the retrieved results.
- Use detail_title for the product name and price_usd for price.
- If the user asks for a price range, return only the matched product titles in that range.
- Use the evidence text only to support the answer; do not invent missing facts.
- Every factual product statement must use source evidence IDs like [S12] when cited.
- Do not give personal dental or medical advice.
- Keep Philips Sonicare and Oral-B claims clearly attributed.

Question:
{question}

Retrieved metadata and snippets:
{_citation_block(candidates[:10])}

Answer:
""".strip()
                try:
                    raw = llm(prompt)[0]["generated_text"]
                    answer = raw.split("Answer:", 1)[-1].strip() or answer
                except Exception:
                    pass
            return {
                "answer": answer,
                "citations": [best.get("evidence_id", "")],
                "hits": candidates[:10],
                "refused": False,
                "unsupported_claims": [],
            }

    hits = retriever.search(question, top_k=top_k)

    if not hits:
        return {
            "answer": "Not found in sources.",
            "citations": [],
            "hits": [],
            "refused": False,
            "unsupported_claims": [],
        }

    context = _citation_block(hits)
    allowed_ids = {h["evidence_id"] for h in hits}

    if llm is not None:
        prompt = f"""
You are a grounded competitive-intelligence assistant.

Rules:
- Use ONLY the evidence supplied below.
- Do not use general knowledge.
- Do not infer missing specifications.
- If the evidence does not support the requested fact, say exactly:
  "Not found in sources."
- When the user asks for the "best" or "highest-rated" product, prioritize the retrieved product metadata with the highest rating_value; the name should come from detail_title and the numeric rating should come from rating_value.
- When the user asks for a price range, return only the matched product titles in that range.
- Every factual product statement must end with one or more evidence IDs such as [S12].
- Never invent an evidence ID.
- Do not give personal medical or dental advice.
- Do not declare a product "best", "winner", "superior", or "recommended" without citing the rating metadata in the retrieved evidence.
- Keep Philips Sonicare and Oral-B claims clearly attributed.

Question:
{question}

Evidence:
{context}

Answer:
""".strip()

        try:
            raw = llm(prompt)[0]["generated_text"]
            answer = raw.split("Answer:", 1)[-1].strip()
        except Exception:
            answer = ""

        valid_ids = _valid_citation_ids(answer, allowed_ids)
        if not answer or not valid_ids:
            answer = deterministic_answer(question, hits)

    else:
        answer = deterministic_answer(question, hits)

    answer = normalize_whitespace(answer)
    unsupported = detect_unsupported_claims(answer, hits)
    citations = sorted(_valid_citation_ids(answer, allowed_ids))

    return {
        "answer": answer,
        "citations": citations,
        "hits": hits,
        "refused": False,
        "unsupported_claims": unsupported,
    }


def deterministic_answer(
    question: str,
    hits: list[dict[str, Any]],
) -> str:
    """
    Safe fallback: report retrieved evidence rather than inventing a conclusion.
    """
    lines = [
        "Based on the retrieved US public-source evidence:",
    ]

    for hit in hits[:6]:
        lines.append(
            f"- {hit['brand']} — {hit['product_name']}: "
            f"{hit['snippet']} [{hit['evidence_id']}]"
        )

    lines.append(
        "Please note: "
        "A fact not represented in these sources is treated as "
        "\"Not found in sources.\""
    )
    return "\n".join(lines)


def build_feature_comparison(
    records: list[dict[str, Any]],
    question: str | None = None,
) -> list[dict[str, Any]]:
    """Return one metadata row per Philips/Oral-B product for a comparison."""
    features = _comparison_features_for_question(question or "")
    rows = []

    for record in records:
        brand = normalize_brand(record.get("brand"))
        if brand not in {"Philips Sonicare", "Oral-B"}:
            continue

        row = {
            "Brand": brand,
            "Product": normalize_product_name(record),
            "Source": normalize_whitespace(
                record.get("source_url") or record.get("product_url") or record.get("listing_url")
            ) or "Not found in sources",
        }
        for feature in features:
            value = _comparison_value(record, feature)
            if feature in {"price_usd", "rating_value"}:
                value = _coerce_float(value)
            elif feature in {"listing_brush_modes_count", "listing_intensities_count"}:
                numeric_value = _coerce_float(value)
                value = int(numeric_value) if numeric_value is not None and numeric_value.is_integer() else numeric_value
            else:
                value = normalize_whitespace(value)
            row[FEATURE_LABELS.get(feature, feature)] = value if value not in (None, "") else "Not found in sources"
        rows.append(row)

    return rows


EVALUATION_QUESTIONS = [
    {
        "question": "Compare app connectivity between Philips Sonicare and Oral-B products.",
        "must_retrieve": ["Philips Sonicare", "Oral-B"],
        "must_refuse": False,
    },
    {
        "question": "Compare pressure sensing between the two brands.",
        "must_retrieve": ["Philips Sonicare", "Oral-B"],
        "must_refuse": False,
    },
    {
        "question": "Which products have app connectivity?",
        "must_retrieve": [],
        "must_refuse": False,
    },
    {
        "question": "Compare the published brush modes.",
        "must_retrieve": [],
        "must_refuse": False,
    },
    {
        "question": "Compare timer features.",
        "must_retrieve": [],
        "must_refuse": False,
    },
    {
        "question": "Compare battery-life information.",
        "must_retrieve": [],
        "must_refuse": False,
    },
    {
        "question": "Compare published plaque-removal claims.",
        "must_retrieve": [],
        "must_refuse": False,
    },
    {
        "question": "Compare published gum-care claims.",
        "must_retrieve": [],
        "must_refuse": False,
    },
    {
        "question": "Compare published stain-removal claims.",
        "must_retrieve": [],
        "must_refuse": False,
    },
    {
        "question": "Show the published prices for relevant products from both brands.",
        "must_retrieve": ["Philips Sonicare", "Oral-B"],
        "must_refuse": False,
    },
    {
        "question": "What is the battery life of a product if it is not stated on its US source page?",
        "must_retrieve": [],
        "must_refuse": False,
    },
    {
        "question": "What should I use for my sensitive gums?",
        "must_retrieve": [],
        "must_refuse": True,
    },
    {
        "question": "Recommend the best toothbrush for my teeth.",
        "must_retrieve": [],
        "must_refuse": True,
    },
    {
        "question": "Does Oral-B have a product with pressure sensing?",
        "must_retrieve": ["Oral-B"],
        "must_refuse": False,
    },
    {
        "question": "Does Philips Sonicare publish app-connectivity information?",
        "must_retrieve": ["Philips Sonicare"],
        "must_refuse": False,
    },
]


def run_evaluation(
    retriever: HybridRetriever,
    llm: Any = None,
) -> dict[str, Any]:
    results = []
    retrieval_hits = 0
    citation_pass = 0
    refusal_pass = 0
    unsupported_pass = 0

    for case in EVALUATION_QUESTIONS:
        result = answer_question(case["question"], retriever, llm=llm)
        hit_brands = {h.get("brand") for h in result["hits"]}

        if case["must_retrieve"]:
            retrieval_ok = all(
                brand in hit_brands for brand in case["must_retrieve"]
            )
        else:
            retrieval_ok = len(result["hits"]) > 0 or case["must_refuse"]

        if retrieval_ok:
            retrieval_hits += 1

        citation_ok = (
            result["refused"]
            or (
                len(result["citations"]) > 0
                and all(
                    cid in {h["evidence_id"] for h in result["hits"]}
                    for cid in result["citations"]
                )
            )
        )
        if citation_ok:
            citation_pass += 1

        refusal_ok = result["refused"] == case["must_refuse"]
        if refusal_ok:
            refusal_pass += 1

        unsupported_ok = len(result["unsupported_claims"]) == 0
        if unsupported_ok:
            unsupported_pass += 1

        results.append({
            "question": case["question"],
            "retrieval_ok": retrieval_ok,
            "citation_ok": citation_ok,
            "refusal_ok": refusal_ok,
            "unsupported_claims_ok": unsupported_ok,
            "answer": result["answer"],
            "citations": result["citations"],
            "unsupported_claims": result["unsupported_claims"],
        })

    total = len(EVALUATION_QUESTIONS)

    return {
        "total_questions": total,
        "retrieval_hit_rate": round(retrieval_hits / total, 3),
        "citation_pass_rate": round(citation_pass / total, 3),
        "refusal_pass_rate": round(refusal_pass / total, 3),
        "unsupported_claim_check_pass_rate": round(
            unsupported_pass / total, 3
        ),
        "results": results,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Grounded Philips Sonicare vs Oral-B competitive intelligence copilot."
    )
    parser.add_argument(
        "--data-dir",
        default=None,
        help="Root data directory containing philips/ and oralb/ CSVs.",
    )
    parser.add_argument(
        "--question",
        default=None,
        help="Ask one comparison question.",
    )
    parser.add_argument(
        "--evaluate",
        action="store_true",
        help="Run the 15-question evaluation suite.",
    )
    parser.add_argument(
        "--use-llm",
        action="store_true",
        help="Use the local Qwen model for answer generation.",
    )
    parser.add_argument(
        "--export-json",
        default=None,
        help="Optional output path for evaluation JSON.",
    )
    args = parser.parse_args()

    if args.data_dir:
        data_dir = Path(args.data_dir)
    else:
        data_dir = Path(__file__).resolve().parents[1] / "data"

    records = load_product_records(data_dir)

    if not records:
        raise SystemExit(
            f"No product CSV records found under {data_dir}. "
            "Expected data/philips/philips_products_flat.csv and "
            "data/oralb/oralb_products_flat.csv."
        )

    validation = validate_dataset(records)

    if not validation["minimum_met"]:
        raise SystemExit(
            "Case-study requirement not met: at least 8 Philips Sonicare "
            "and 8 Oral-B products are required."
        )

    if validation["invalid_source_count"]:
        raise SystemExit(
            "Case-study source boundary violated: one or more records are "
            "not from the allowed US Philips/Oral-B domains."
        )

    if not args.question and not args.evaluate:
        try:
            args.question = input("Type your comparison question: ").strip()
        except EOFError:
            return
        if not args.question:
            return

    documents = build_evidence_documents(records)
    retriever = HybridRetriever(documents, product_records=records)
    llm = _load_published_llm() if args.use_llm else None

    if args.evaluate:
        report = run_evaluation(retriever, llm=llm)
        print(json.dumps(report, indent=2))

        if args.export_json:
            Path(args.export_json).write_text(
                json.dumps(report, indent=2),
                encoding="utf-8",
            )
        return

    if args.question:
        result = answer_question(args.question, retriever, llm=llm, top_k=5)
        print(normalize_whitespace(result["answer"]))
        print("\nCitations:")
        print(", ".join(result["citations"]) or "None")

        if result["unsupported_claims"]:
            print("\nGrounding warnings:")
            for issue in result["unsupported_claims"]:
                print("-", issue)
        return

    return


if __name__ == "__main__":
    main()
